[package]
name = "project-diamond-hands"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
anyhow = "1.0"
rust_decimal = { version = "1.33", features = ["serde-with-str"] }
